image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn install
    command: yarn start:prod

ports:
  - name: serviceEndpointPort
    description: This port is exposed to the public so the app can interact with wallets and such
    port: 8020
    onOpen: ignore
    visibility: public

  - name: localhostPort
    description: This port is kept local and is the one that serves up the proof request
    port: 3000
    onOpen: notify
    visibility: private
